networks:
  vid_trans_network:

services:
  flask_api:
    build:
      context: ./backend/flask_api
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://user123:U4yfJPqa@db:3306/flask_db
      REDIS_URL: redis://redis:6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: U4yfJPqa
    volumes:
      - res_data:/app/uploads
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - vid_trans_network
  
  
  subs_generator:
    build:
      context: ./backend/subs_generator
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: U4yfJPqa
    volumes:
      - res_data:/app/uploads
    depends_on:
      - rabbitmq
    networks:
      - vid_trans_network
  
  
  voice_generator:
    build:
      context: ./backend/voice_generator
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: U4yfJPqa
    volumes:
      - res_data:/app/uploads
    depends_on:
      - rabbitmq
    networks:
      - vid_trans_network
  
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - vid_trans_network
  
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ajgkRpo1
      MYSQL_DATABASE: flask_db
      MYSQL_USER: user123
      MYSQL_PASSWORD: U4yfJPqa
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vid_trans_network

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - vid_trans_network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "127.0.0.1:5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: U4yfJPqa
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - vid_trans_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - flask_api
      - frontend
      - rabbitmq
      - redis
      - db
    networks:
      - vid_trans_network

      
volumes:
  mysql_data:
  rabbitmq_data:
  res_data:
